### ISSUE TITLE
Add a readme

### ISSUE THREAD

**Issue by Ky1e** [CaptEmulation/coc-slack-bot#1]
I'm just now getting spun on on slack and a readme would be GREATLY appreciated as this is currently the only solution out there for integrating a slackbot for coc that I am aware of.

**Comment by CaptEmulation** [comment]
hey sorry... just noticed this.  I will update the repo with some set-up instructions this weekend.

**Comment by Ky1e** [comment]
Hey no problem. This is a REALLY neat project. Thanks for the work you've done.
-Kyle

**Comment by CaptEmulation** [comment]
Fair warning... I worked on this project only briefly while I was in the hospital and have not had much time since then.  The code is incomplete and buggy.

**Comment by Ky1e** [comment]
Looking through it I see the bulk of it is there. I'm not to spun up on CoC's api but in terms of a boilerplate I'd say this is awesome. I'll work through and submit pull requests as I go.

**Comment by CaptEmulation** [comment]
The API is the easy part.  I also have a module for that: https://github.com/CaptEmulation/clash-of-clans-api.  The part that is not working is the war stat tracking.

**Comment by Ky1e** [comment]
Is it saying that it is not authorized? What do the log errors say?

**Comment by CaptEmulation** [comment]
- Checked out project
- fixed a crasher/blocker bug
- Moved a hard-coded value and an environment variable into config.js
- Added an example config.js.  There was no way you could have known about that...
- Got it running on a fresh computer (which already had all software dependencies installed)
- Added README.md and LICENSE

Good Luck!
